services:
  - type: web
    name: ai-stroke-risk-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    region: oregon
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
